title:             Khinshan Khan
email:             your-email@example.com
description:       Developer · Designer · Writer
author:            Khinshan Khan
baseurl:           "/test"
url:               "http://khinshankhan.com/test"

# Social Profiles
github_username:   kkhan01
facebook_username: khinshan.khan

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
